version: "3"

services:
  price_generator:
    image: price_generator
    environment:
      REDIS_ADDR: "redis:6379"
  price_service:
    image: price_service
  client:
    image: client


  redis:
    image: redis
    ports:
      - "6379:6379"